import { useState } from 'react';
import { Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';

export default function CafeTrial(){
  const [loading,setLoading]=useState(false);
  async function start(){setLoading(true);const {error}=await supabase.rpc('ensure_cafe_subscription');setLoading(false);if(error)return Alert.alert('Could not open your hiring workspace',error.message);router.replace('/home')}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.wrap}><Text style={s.brand}>Barista<Text style={s.accent}>Match</Text></Text><View style={s.plan}><View style={s.glow}/><View style={s.head}><View style={s.crown}><Text style={s.crownText}>♕</Text></View><View><Text style={s.kicker}>CAFÉ ACCESS</Text><Text style={s.title}>Start hiring{`\n`}with confidence.</Text></View></View><View style={s.free}><Text style={s.freeText}>Payments are paused</Text></View><Text style={s.price}>Your café has <Text style={s.priceAccent}>full access</Text></Text><Text style={s.copy}>Discover local baristas, publish jobs, create mutual matches, and message your connections. You will not be charged.</Text><View style={s.benefits}><Benefit text="No payment required"/><Benefit text="Full hiring access"/><Benefit text="Private messaging"/><Benefit text="We’ll announce billing before it starts"/></View><Pressable disabled={loading} onPress={start} style={[s.button,loading&&{opacity:.65}]}><Text style={s.buttonText}>{loading?'Opening your workspace…':'Open hiring workspace →'}</Text></Pressable></View><Text style={s.note}>Stripe checkout is disabled until further notice.</Text></ScrollView></SafeAreaView>
}
function Benefit({text}:{text:string}){return <View style={s.benefit}><Text style={s.check}>✓</Text><Text style={s.benefitText}>{text}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fffaf4'},wrap:{flexGrow:1,justifyContent:'center',padding:20},brand:{fontSize:24,fontWeight:'900',color:'#321708',textAlign:'center',marginBottom:22},accent:{color:'#b9561c'},plan:{position:'relative',overflow:'hidden',backgroundColor:'#421d0b',borderRadius:28,padding:26,shadowColor:'#321708',shadowOpacity:.2,shadowRadius:24,shadowOffset:{width:0,height:12},elevation:8},glow:{position:'absolute',right:-70,bottom:-90,width:210,height:210,borderRadius:105,backgroundColor:'#d8641e',opacity:.15},head:{flexDirection:'row',alignItems:'center',gap:13},crown:{width:56,height:56,borderRadius:28,borderWidth:2,borderColor:'#ed7126',alignItems:'center',justifyContent:'center'},crownText:{fontSize:29,color:'#f18a49'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.8,color:'#dab59d',marginBottom:5},title:{fontFamily:'Georgia',fontSize:29,lineHeight:31,fontWeight:'700',color:'#fff'},free:{alignSelf:'flex-start',marginTop:25,backgroundColor:'#f8e9dd',borderRadius:99,paddingHorizontal:13,paddingVertical:8},freeText:{fontSize:11,fontWeight:'900',color:'#54250d'},price:{fontSize:23,lineHeight:29,fontWeight:'900',color:'#fff',marginTop:15},priceAccent:{color:'#ff9b5b'},copy:{fontSize:13,lineHeight:20,color:'#ead8cb',marginTop:7},benefits:{marginTop:20,gap:9},benefit:{flexDirection:'row',alignItems:'center'},check:{fontWeight:'900',color:'#ff9b5b',marginRight:8},benefitText:{fontSize:12,color:'#f3e7dd'},button:{marginTop:23,backgroundColor:'#d8641e',borderRadius:14,paddingVertical:15,alignItems:'center'},buttonText:{fontSize:14,fontWeight:'900',color:'#fff'},note:{fontSize:11,color:'#78685e',textAlign:'center',marginTop:14}});
