import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Image,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { getCurrentContext } from '@/lib/session';
import { AppBottomNav } from '@/components/AppBottomNav';

type Candidate={id:string;job_id:string;status:string;job?:any;barista?:any};
export default function CandidatesScreen(){
 const [loading,setLoading]=useState(true),[items,setItems]=useState<Candidate[]>([]),[index,setIndex]=useState(0),[busy,setBusy]=useState(false);
 const current=items[index];
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);const {user,role}=await getCurrentContext();if(!user)return router.replace('/login');if(role!=='cafe_owner_manager'){setLoading(false);return}
  const {data,error}=await supabase.from('applications').select('id,job_id,status,created_at,barista:profiles!applications_barista_id_fkey(id,display_name,location,bio,skills,availability,experience,pay_expectation,video_path,avatar_url),job:jobs!inner(id,title,owner_id)').eq('job.owner_id',user.id).eq('status','interested').order('created_at',{ascending:true});
  if(error)Alert.alert('Could not load candidates',error.message);setItems((data||[]) as Candidate[]);setIndex(0);setLoading(false)}
 async function decide(decision:'matched'|'declined') {if(!current||busy)return;setBusy(true);const {error}=await supabase.from('applications').update({status:decision}).eq('id',current.id);setBusy(false);if(error)return Alert.alert('Could not update candidate',error.message);if(decision==='matched')return router.push({pathname:'/match-success',params:{applicationId:current.id,name:current.barista?.display_name||'Barista'}});setIndex(i=>i+1)}
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#321708"/></View></SafeAreaView>;
 if(!current)return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.logo}>Barista<Text style={s.accent}>Match</Text></Text><Text style={s.kicker}>CANDIDATES</Text></View><View style={s.empty}><Text style={s.emptyIcon}>☕</Text><Text style={s.emptyTitle}>You’re caught up</Text><Text style={s.emptyCopy}>New baristas who are interested in your jobs will appear here.</Text><Pressable style={s.primary} onPress={load}><Text style={s.primaryText}>Refresh</Text></Pressable></View><AppBottomNav active="candidates" role="cafe_owner_manager"/></SafeAreaView>;
 const b=current.barista||{},skills=(b.skills||[]).slice(0,4);
 return <SafeAreaView style={s.safe}><View style={s.header}><View><Text style={s.logo}>Barista<Text style={s.accent}>Match</Text></Text><Text style={s.kicker}>REVIEW · MATCH · BREW</Text></View><Text style={s.count}>{index+1}/{items.length}</Text></View><ScrollView contentContainerStyle={s.wrap}><View style={s.card}>{b.avatar_url?<Image source={{uri:b.avatar_url}} style={s.photo}/>:<View style={s.photoFallback}><Text style={{fontSize:70}}>👤</Text></View>}<View style={s.body}><Text style={s.name}>{b.display_name||'Barista'}</Text><Text style={s.job}>Interested in {current.job?.title||'your café role'}</Text><Text style={s.meta}>📍 {b.location||'Location not added'}</Text><View style={s.tags}>{skills.map((x:string)=><View style={s.tag} key={x}><Text style={s.tagText}>{x}</Text></View>)}</View><Info label="Experience" value={b.experience||'Not added yet'}/><Info label="Availability" value={b.availability||'Not added yet'}/><Info label="Desired pay" value={b.pay_expectation||'Not added yet'}/>{b.bio?<Info label="About" value={b.bio}/>:null}{b.video_path?<View style={s.video}><Text style={s.videoTitle}>🎥 Coffee showcase available</Text><Text style={s.videoCopy}>This barista has uploaded a coffee showcase video.</Text></View>:null}</View></View></ScrollView><View style={s.actions}><Pressable disabled={busy} onPress={()=>decide('declined')} style={[s.action,s.pass]}><Text style={s.passText}>×</Text></Pressable><Pressable disabled={busy} onPress={()=>decide('matched')} style={[s.action,s.match]}><Text style={s.matchText}>♥</Text></Pressable></View><AppBottomNav active="candidates" role="cafe_owner_manager"/></SafeAreaView>}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fbf7f1'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{padding:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{fontSize:24,fontWeight:'900',color:'#321708'},accent:{color:'#a95820'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#9a7c68',marginTop:2},count:{fontWeight:'800',color:'#8b7769'},wrap:{padding:18,paddingBottom:10},card:{backgroundColor:'#fff',borderRadius:26,overflow:'hidden',borderWidth:1,borderColor:'#eadfd5'},photo:{height:250,width:'100%',backgroundColor:'#eee'},photoFallback:{height:250,backgroundColor:'#2a180f',alignItems:'center',justifyContent:'center'},body:{padding:20},name:{fontSize:29,fontWeight:'900',color:'#24150d'},job:{fontSize:15,fontWeight:'700',color:'#a95820',marginTop:3},meta:{fontSize:14,color:'#746a61',marginTop:12},tags:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:14},tag:{backgroundColor:'#f3e8de',paddingHorizontal:10,paddingVertical:7,borderRadius:999},tagText:{fontSize:11,fontWeight:'800',color:'#6d381c'},info:{borderTopWidth:1,borderTopColor:'#f0e7df',paddingTop:13,marginTop:13},infoLabel:{fontSize:11,fontWeight:'900',textTransform:'uppercase',letterSpacing:1,color:'#9b8778'},infoValue:{fontSize:14,lineHeight:20,color:'#3c3029',marginTop:5},video:{marginTop:15,backgroundColor:'#321708',borderRadius:16,padding:15},videoTitle:{color:'#fff',fontWeight:'900'},videoCopy:{color:'#dac9bd',fontSize:12,marginTop:4},actions:{height:82,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:30},action:{width:62,height:62,borderRadius:40,alignItems:'center',justifyContent:'center'},pass:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e4d6cb'},match:{backgroundColor:'#2f7c42'},passText:{fontSize:40,color:'#c84b3e',marginTop:-5},matchText:{fontSize:29,color:'#fff'},primary:{backgroundColor:'#321708',borderRadius:14,paddingHorizontal:24,paddingVertical:14,marginTop:20},primaryText:{color:'#fff',fontWeight:'900'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:28},emptyIcon:{fontSize:48},emptyTitle:{fontSize:27,fontWeight:'900',color:'#321708',marginTop:15},emptyCopy:{fontSize:15,lineHeight:22,color:'#746a61',textAlign:'center',maxWidth:320,marginTop:8}});
