import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { getCurrentContext } from '@/lib/session';
import { AppBottomNav } from '@/components/AppBottomNav';

type Job={id:string;title:string;location:string|null;pay_min:number|null;schedule:string|null;active:boolean};

export default function JobsScreen(){
  const [loading,setLoading]=useState(true);
  const [jobs,setJobs]=useState<Job[]>([]);
  const load=useCallback(async()=>{setLoading(true);const {user,role}=await getCurrentContext();if(!user)return router.replace('/login');if(role!=='cafe_owner_manager')return router.replace('/home');const {data,error}=await supabase.from('jobs').select('id,title,location,pay_min,schedule,active').eq('owner_id',user.id).order('created_at',{ascending:false});setLoading(false);if(error)return Alert.alert('Could not load jobs',error.message);setJobs((data||[]) as Job[])},[]);
  useEffect(()=>{load()},[load]);
  function close(job:Job){Alert.alert('Close this job?',`${job.title} will stop appearing to baristas.`,[{text:'Cancel',style:'cancel'},{text:'Close job',style:'destructive',onPress:async()=>{const {user}=await getCurrentContext();if(!user)return router.replace('/login');const {error}=await supabase.from('jobs').update({active:false}).eq('id',job.id).eq('owner_id',user.id);if(error)return Alert.alert('Could not close job',error.message);load()}}])}
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#321708"/></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.title}>Job posts</Text><Text style={s.sub}>Create, edit, and close café roles</Text></View><Pressable style={s.add} onPress={()=>router.push('/post-job')}><Text style={s.addText}>＋</Text></Pressable></View><ScrollView contentContainerStyle={s.wrap}>{jobs.length?jobs.map(job=><View key={job.id} style={s.card}><View style={s.cardTop}><View style={{flex:1}}><Text style={s.jobTitle}>{job.title}</Text><Text style={s.meta}>{job.location||'Location not added'} · {job.pay_min==null?'Pay not added':`$${job.pay_min}/hour`}</Text><Text style={s.meta}>{job.schedule||'Schedule not added'}</Text></View><View style={[s.status,!job.active&&s.closed]}><Text style={[s.statusText,!job.active&&s.closedText]}>{job.active?'Active':'Closed'}</Text></View></View><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/post-job',params:{jobId:job.id}})}><Text style={s.secondaryText}>Edit</Text></Pressable>{job.active?<Pressable style={s.secondary} onPress={()=>close(job)}><Text style={s.dangerText}>Close job</Text></Pressable>:null}</View></View>):<View style={s.empty}><Text style={s.emptyIcon}>📋</Text><Text style={s.emptyTitle}>No jobs yet</Text><Text style={s.emptyCopy}>Post your first role to start meeting local baristas.</Text><Pressable style={s.primary} onPress={()=>router.push('/post-job')}><Text style={s.primaryText}>Post a job</Text></Pressable></View>}</ScrollView><AppBottomNav active="home" role="cafe_owner_manager"/></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fbf7f1'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{minHeight:72,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#eadfd5',backgroundColor:'#fff'},back:{fontSize:36,color:'#321708'},title:{fontSize:21,fontWeight:'900',color:'#321708'},sub:{fontSize:11,color:'#786a61',marginTop:2},add:{marginLeft:'auto',width:42,height:42,borderRadius:14,backgroundColor:'#321708',alignItems:'center',justifyContent:'center'},addText:{fontSize:25,color:'#fff'},wrap:{padding:18,paddingBottom:32},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#eadfd5',borderRadius:18,padding:16,marginBottom:12},cardTop:{flexDirection:'row',gap:10},jobTitle:{fontSize:18,fontWeight:'900',color:'#321708'},meta:{fontSize:12,lineHeight:18,color:'#746a61',marginTop:3},status:{backgroundColor:'#e8f1e4',borderRadius:99,paddingHorizontal:10,paddingVertical:6,alignSelf:'flex-start'},statusText:{fontSize:9,fontWeight:'900',color:'#41713c'},closed:{backgroundColor:'#eee8e3'},closedText:{color:'#786a61'},actions:{flexDirection:'row',gap:9,marginTop:14},secondary:{borderWidth:1,borderColor:'#d6c2b3',borderRadius:11,paddingHorizontal:15,paddingVertical:10},secondaryText:{fontWeight:'900',color:'#321708'},dangerText:{fontWeight:'900',color:'#9c2d27'},empty:{alignItems:'center',paddingVertical:70,paddingHorizontal:24},emptyIcon:{fontSize:52},emptyTitle:{fontSize:25,fontWeight:'900',color:'#321708',marginTop:15},emptyCopy:{fontSize:14,lineHeight:20,color:'#746a61',textAlign:'center',marginTop:7},primary:{backgroundColor:'#321708',borderRadius:13,paddingHorizontal:20,paddingVertical:13,marginTop:20},primaryText:{color:'#fff',fontWeight:'900'}});
