import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { getCurrentContext,AppRole } from '@/lib/session';
import { AppBottomNav } from '@/components/AppBottomNav';

type MatchRow={id:string;kind:'discovery'|'application';name:string;detail:string};
export default function Matches(){
  const [loading,setLoading]=useState(true),[rows,setRows]=useState<MatchRow[]>([]),[role,setRole]=useState<AppRole>('barista');useEffect(()=>{load()},[]);
  async function load(){const {user,role:r}=await getCurrentContext();if(!user)return router.replace('/login');const accountRole=r||'barista';setRole(accountRole);let legacyQuery=supabase.from('applications').select('id,status,barista:profiles!applications_barista_id_fkey(display_name),job:jobs!inner(title,owner_id,owner:profiles!jobs_owner_id_fkey(cafe_name))').eq('status','matched');if(accountRole==='barista')legacyQuery=legacyQuery.eq('barista_id',user.id);else legacyQuery=legacyQuery.eq('job.owner_id',user.id);const [legacyResult,mutualResult]=await Promise.all([legacyQuery,supabase.from('discovery_matches').select('id,barista_id,cafe_id,barista:profiles!discovery_matches_barista_id_fkey(display_name,location),cafe:profiles!discovery_matches_cafe_id_fkey(cafe_name,location)').or(`barista_id.eq.${user.id},cafe_id.eq.${user.id}`).order('created_at',{ascending:false})]);setLoading(false);if(legacyResult.error||mutualResult.error)return Alert.alert('Could not load matches',(legacyResult.error||mutualResult.error)?.message);const mutual=(mutualResult.data||[]).map((item:any)=>{const person=accountRole==='barista'?item.cafe:item.barista;return {id:item.id,kind:'discovery' as const,name:accountRole==='barista'?(person?.cafe_name||'Café'):(person?.display_name||'Barista'),detail:person?.location||'Mutual profile match'}});const legacy=(legacyResult.data||[]).map((item:any)=>({id:item.id,kind:'application' as const,name:accountRole==='barista'?(item.job?.owner?.cafe_name||'Café'):(item.barista?.display_name||'Barista'),detail:item.job?.title||'Matched connection'}));setRows([...mutual,...legacy])}
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color="#321708" size="large"/></View></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.title}>Matches</Text><Text style={s.sub}>Both sides agreed — start a conversation</Text></View><ScrollView contentContainerStyle={s.list}>{rows.length?rows.map(x=><Pressable key={`${x.kind}-${x.id}`} style={s.row} onPress={()=>router.push({pathname:'/chat/[id]',params:{id:x.id,kind:x.kind}})}><View style={s.avatar}><Text style={{fontSize:22}}>{role==='barista'?'☕':'👤'}</Text></View><View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.detail} · Matched</Text></View><Text style={s.chev}>›</Text></Pressable>):<View style={s.empty}><Text style={{fontSize:48}}>🤝</Text><Text style={s.emptyTitle}>No matches yet</Text><Text style={s.emptyCopy}>Use Discover and show interest. A match appears when they choose you too.</Text></View>}</ScrollView><AppBottomNav active="matches" role={role}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fbf7f1'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{padding:20,paddingBottom:10},title:{fontSize:31,fontWeight:'900',color:'#321708'},sub:{fontSize:14,color:'#746a61',marginTop:4},list:{padding:18,paddingBottom:30},row:{flexDirection:'row',alignItems:'center',gap:13,backgroundColor:'#fff',borderWidth:1,borderColor:'#eadfd5',borderRadius:18,padding:15,marginBottom:10},avatar:{width:48,height:48,borderRadius:24,backgroundColor:'#f3e8de',alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'900',color:'#24150d'},meta:{fontSize:12,color:'#746a61',marginTop:4},chev:{fontSize:29,color:'#a95820'},empty:{alignItems:'center',paddingTop:100},emptyTitle:{fontSize:25,fontWeight:'900',color:'#321708',marginTop:15},emptyCopy:{fontSize:14,lineHeight:20,textAlign:'center',color:'#746a61',marginTop:6}});
