import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { getCurrentContext,AppRole } from '@/lib/session';
import { AppBottomNav } from '@/components/AppBottomNav';

type Conversation={id:string;kind:'discovery'|'application';name:string;preview:string;created_at?:string};
export default function Messages(){
  const [loading,setLoading]=useState(true),[rows,setRows]=useState<Conversation[]>([]),[role,setRole]=useState<AppRole>('barista');useEffect(()=>{load()},[]);
  async function load(){const {user,role:r}=await getCurrentContext();if(!user)return router.replace('/login');const accountRole=r||'barista';setRole(accountRole);let legacyQuery=supabase.from('applications').select('id,barista:profiles!applications_barista_id_fkey(display_name),job:jobs!inner(title,owner_id,owner:profiles!jobs_owner_id_fkey(cafe_name))').eq('status','matched');if(accountRole==='barista')legacyQuery=legacyQuery.eq('barista_id',user.id);else legacyQuery=legacyQuery.eq('job.owner_id',user.id);const [legacyResult,mutualResult]=await Promise.all([legacyQuery,supabase.from('discovery_matches').select('id,barista_id,cafe_id,barista:profiles!discovery_matches_barista_id_fkey(display_name),cafe:profiles!discovery_matches_cafe_id_fkey(cafe_name)').or(`barista_id.eq.${user.id},cafe_id.eq.${user.id}`).order('created_at',{ascending:false})]);if(legacyResult.error||mutualResult.error){setLoading(false);return Alert.alert('Could not load messages',(legacyResult.error||mutualResult.error)?.message)}const legacyIds=(legacyResult.data||[]).map((x:any)=>x.id),mutualIds=(mutualResult.data||[]).map((x:any)=>x.id);const [legacyMessages,mutualMessages]=await Promise.all([legacyIds.length?supabase.from('messages').select('application_id,body,created_at').in('application_id',legacyIds).order('created_at',{ascending:false}):Promise.resolve({data:[],error:null}),mutualIds.length?supabase.from('discovery_messages').select('match_id,body,created_at').in('match_id',mutualIds).order('created_at',{ascending:false}):Promise.resolve({data:[],error:null})]);if(legacyMessages.error||mutualMessages.error){setLoading(false);return Alert.alert('Could not load messages',(legacyMessages.error||mutualMessages.error)?.message)}const mutual=(mutualResult.data||[]).map((item:any)=>({id:item.id,kind:'discovery' as const,name:accountRole==='barista'?(item.cafe?.cafe_name||'Café'):(item.barista?.display_name||'Barista'),preview:(mutualMessages.data||[]).find((m:any)=>m.match_id===item.id)?.body||'Start the conversation'}));const legacy=(legacyResult.data||[]).map((item:any)=>({id:item.id,kind:'application' as const,name:accountRole==='barista'?(item.job?.owner?.cafe_name||'Café'):(item.barista?.display_name||'Barista'),preview:(legacyMessages.data||[]).find((m:any)=>m.application_id===item.id)?.body||item.job?.title||'Start the conversation'}));setRows([...mutual,...legacy]);setLoading(false)}
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#321708"/></View></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.title}>Messages</Text><Text style={s.sub}>Private conversations with mutual matches</Text></View><ScrollView contentContainerStyle={s.list}>{rows.length?rows.map(x=><Pressable key={`${x.kind}-${x.id}`} style={s.row} onPress={()=>router.push({pathname:'/chat/[id]',params:{id:x.id,kind:x.kind}})}><View style={s.avatar}><Text style={{fontSize:22}}>{role==='barista'?'☕':'👤'}</Text></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={s.name}>{x.name}</Text><Text numberOfLines={1} style={s.preview}>{x.preview}</Text></View><Text style={s.chev}>›</Text></Pressable>):<View style={s.empty}><Text style={{fontSize:48}}>💬</Text><Text style={s.emptyTitle}>No conversations yet</Text><Text style={s.emptyCopy}>A private conversation opens after both sides match.</Text></View>}</ScrollView><AppBottomNav active="messages" role={role}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fbf7f1'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{padding:20,paddingBottom:10},title:{fontSize:31,fontWeight:'900',color:'#321708'},sub:{fontSize:14,color:'#746a61',marginTop:4},list:{padding:18,paddingBottom:30},row:{flexDirection:'row',alignItems:'center',gap:13,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#eee4da',paddingVertical:15},avatar:{width:50,height:50,borderRadius:25,backgroundColor:'#f3e8de',alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'900',color:'#24150d'},preview:{fontSize:13,color:'#746a61',marginTop:5},chev:{fontSize:28,color:'#a95820'},empty:{alignItems:'center',paddingTop:100},emptyTitle:{fontSize:25,fontWeight:'900',color:'#321708',marginTop:15},emptyCopy:{fontSize:14,color:'#746a61',marginTop:6,textAlign:'center'}});
