from pathlib import Path

# Login
p=Path('login.html'); s=p.read_text()
s=s.replace('.google-g{font:900 19px Arial;color:#4285f4}', '.google-g{font:900 19px Arial;color:#4285f4}.social-stack{display:grid;gap:10px}.apple-mark{font:900 22px/1 Arial,sans-serif;color:#111}')
s=s.replace('<button class="button social" id="google" type="button"><span class="google-g">G</span>Continue with Google</button>', '<div class="social-stack"><button class="button social" id="google" type="button"><span class="google-g">G</span>Continue with Google</button><button class="button social" id="apple" type="button"><span class="apple-mark" aria-hidden="true">●</span>Continue with Apple</button></div>')
s=s.replace('BaristaMatch never sees your Google password.', 'BaristaMatch never sees your Google or Apple password.')
needle="document.getElementById('google').onclick=async event=>{if(!client)return setStatus('Login is still loading. Please try again.',true);event.currentTarget.disabled=true;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:'https://www.baristajobmatch.com/dashboard.html'}});event.currentTarget.disabled=false;if(error)setStatus('Google login could not start. Please try email and password.',true)};"
apple=needle+"document.getElementById('apple').onclick=async event=>{if(!client)return setStatus('Login is still loading. Please try again.',true);event.currentTarget.disabled=true;const {error}=await client.auth.signInWithOAuth({provider:'apple',options:{redirectTo:'https://www.baristajobmatch.com/dashboard.html'}});event.currentTarget.disabled=false;if(error)setStatus('Apple login could not start. Please try email and password.',true)};"
assert needle in s
s=s.replace(needle,apple)
p.write_text(s)

# Signup
p=Path('signup.html'); s=p.read_text()
s=s.replace('.google{background:#fff;color:#28160d;border:1px solid #bfae9f;display:flex;justify-content:center;align-items:center;gap:10px}.google span{font-weight:900;color:#4285f4;font-size:18px}', '.google,.apple{background:#fff;color:#28160d;border:1px solid #bfae9f;display:flex;justify-content:center;align-items:center;gap:10px}.google span{font-weight:900;color:#4285f4;font-size:18px}.apple span{font-weight:900;color:#111;font-size:22px;line-height:1}.social-stack{display:grid;gap:10px}')
s=s.replace('<button class="button google" id="google-signup" type="button"><span>G</span>Continue with Google</button>', '<div class="social-stack"><button class="button google" id="google-signup" type="button"><span>G</span>Continue with Google</button><button class="button apple" id="apple-signup" type="button"><span aria-hidden="true">●</span>Continue with Apple</button></div>')
s=s.replace('BaristaMatch never sees your Google password.', 'BaristaMatch never sees your Google or Apple password.')
s=s.replace("const form=document.getElementById('signup-form'),status=document.getElementById('status'),googleButton=document.getElementById('google-signup');let client;", "const form=document.getElementById('signup-form'),status=document.getElementById('status'),googleButton=document.getElementById('google-signup'),appleButton=document.getElementById('apple-signup');let client;")
s=s.replace('async function finishGoogleSignup(session)', 'async function finishSocialSignup(session)')
s=s.replace('finishGoogleSignup(session)', 'finishSocialSignup(session)').replace('finishGoogleSignup(nextSession)', 'finishSocialSignup(nextSession)')
needle="googleButton.addEventListener('click',async()=>{setStatus();const role=selectedRole(),name=form.elements.name.value.trim(),locationValue=form.elements.location.value.trim();if(!role)return setStatus('Please choose Barista or Café before continuing with Google.',true);if(!name||!locationValue)return setStatus(`Please enter your ${role==='barista'?'name':'café name'} and location before continuing with Google.`,true);if(!client)return setStatus('Account signup is still loading. Please try again.',true);localStorage.setItem('baristamatch_pending_role',role);localStorage.setItem('baristamatch_pending_name',name);localStorage.setItem('baristamatch_pending_location',locationValue);googleButton.disabled=true;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:'https://www.baristajobmatch.com/signup.html?oauth=complete'}});googleButton.disabled=false;if(error){['baristamatch_pending_role','baristamatch_pending_name','baristamatch_pending_location'].forEach(key=>localStorage.removeItem(key));setStatus('Google signup could not start. Please try again or create an account with email.',true)}});"
assert needle in s
apple=needle+"\nappleButton.addEventListener('click',async()=>{setStatus();const role=selectedRole(),name=form.elements.name.value.trim(),locationValue=form.elements.location.value.trim();if(!role)return setStatus('Please choose Barista or Café before continuing with Apple.',true);if(!name||!locationValue)return setStatus(`Please enter your ${role==='barista'?'name':'café name'} and location before continuing with Apple.`,true);if(!client)return setStatus('Account signup is still loading. Please try again.',true);localStorage.setItem('baristamatch_pending_role',role);localStorage.setItem('baristamatch_pending_name',name);localStorage.setItem('baristamatch_pending_location',locationValue);appleButton.disabled=true;const {error}=await client.auth.signInWithOAuth({provider:'apple',options:{redirectTo:'https://www.baristajobmatch.com/signup.html?oauth=complete'}});appleButton.disabled=false;if(error){['baristamatch_pending_role','baristamatch_pending_name','baristamatch_pending_location'].forEach(key=>localStorage.removeItem(key));setStatus('Apple signup could not start. Please try again or create an account with email.',true)}});"
s=s.replace(needle,apple)
p.write_text(s)
