from pathlib import Path
p=Path('dashboard.html');s=p.read_text()
# Add Applications to the barista navigation.
s=s.replace("menu:['Overview','Find Jobs','Matches','Messages','Profile Views','My Profile']","menu:['Overview','Find Jobs','Applications','Matches','Messages','Profile Views','My Profile']")
# Make the profile completion card and barista overview stats actionable.
s=s.replace('<article class="profile-progress-card"><div class="profile-progress-ring"', '<article class="profile-progress-card wow-stat-link" data-go="My Profile" role="button" tabindex="0" aria-label="Open your profile"><div class="profile-progress-ring"',1)
s=s.replace('<article class="wow-stat"><span class="wow-stat-label">Open Jobs</span><strong>${marketJobs.length}</strong><span class="wow-stat-trend">Near your work area</span>', '<article class="wow-stat wow-stat-link" data-go="Find Jobs" role="button" tabindex="0" aria-label="Browse open jobs"><span class="wow-stat-label">Open Jobs</span><strong>${marketJobs.length}</strong><span class="wow-stat-trend">View jobs →</span>',1)
s=s.replace('<article class="wow-stat"><span class="wow-stat-label">Matches</span><strong>${matches}</strong><span class="wow-stat-trend">Connections</span>', '<article class="wow-stat wow-stat-link" data-go="Matches" role="button" tabindex="0" aria-label="View your matches"><span class="wow-stat-label">Matches</span><strong>${matches}</strong><span class="wow-stat-trend">View matches →</span>',1)
s=s.replace('<article class="wow-stat"><span class="wow-stat-label">Applications</span><strong>${applications.length}</strong><span class="wow-stat-trend">All time</span>', '<article class="wow-stat wow-stat-link" data-go="Applications" role="button" tabindex="0" aria-label="Track your applications"><span class="wow-stat-label">Applications</span><strong>${applications.length}</strong><span class="wow-stat-trend">Track status →</span>',1)
# Add a real Applications page for baristas.
marker="Object.defineProperty(sectionPages.barista,'Account Settings',{get:accountSettingsHtml});"
app_fn='''function applicationsHtml(){\n  const rows=applications.map(app=>{const title=escapeHtml(app.job?.title||'Café opportunity'),cafe=escapeHtml(app.job?.owner?.cafe_name||'Café'),status=app.status==='matched'?'Matched ✓':'Interest sent',date=app.created_at?new Date(app.created_at).toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'}):'';return `<div class="item applicant-status-row"><div class="avatar">☕</div><div class="itemtext"><b>${title}</b><small>${cafe} · ${status}${date?` · ${escapeHtml(date)}`:''}</small></div>${app.status==='matched'?'<button class="secondary" data-go="Matches">Open match →</button>':''}</div>`}).join('');return `<div class="section-head"><div><h2>Applications</h2><p>Track the jobs you’re interested in and see when a café matches with you.</p></div></div><article class="card"><h3>Your activity</h3>${rows||'<div class="empty-state"><div class="avatar">↗</div><h3>No applications yet</h3><p>Browse nearby jobs and show interest when you find a good fit.</p><button class="primary" data-go="Find Jobs">Find jobs</button></div>'}</article>`}\nObject.defineProperty(sectionPages.barista,'Applications',{get:applicationsHtml});\n'''
if "Object.defineProperty(sectionPages.barista,'Applications'" not in s:s=s.replace(marker,app_fn+marker,1)
# Small mobile polish for action rows.
if '.applicant-status-row .secondary' not in s:
    s=s.replace('</style>','.applicant-status-row .secondary{white-space:nowrap}@media(max-width:720px){.applicant-status-row{align-items:flex-start}.applicant-status-row .secondary{width:100%;margin-top:8px}}\n</style>',1)
p.write_text(s)
