from pathlib import Path
p=Path('dashboard.html');s=p.read_text()
old="<div class=\"item\"><div class=\"avatar\">👤</div><div class=\"itemtext\"><b>${escapeHtml(app.barista?.display_name||'Barista')}</b><small>${escapeHtml(app.job?.title||'Your job')} · ${escapeHtml(app.barista?.location||'Location not added')} · ${escapeHtml(app.status)}</small></div><button class=\"secondary\" data-view-barista=\"${app.barista_id}\">View</button>${app.status==='interested'?`<button class=\"primary\" data-match-app=\"${app.id}\">Match</button>`:''}</div>"
new="<div class=\"item applicant-item\"><div class=\"applicant-main\"><div class=\"avatar\">👤</div><div class=\"itemtext\"><b>${escapeHtml(app.barista?.display_name||'Barista')}</b><small>${escapeHtml(app.job?.title||'Your job')} · ${escapeHtml(app.barista?.location||'Location not added')} · ${escapeHtml(app.status)}</small></div></div><div class=\"applicant-actions\"><button class=\"secondary\" data-view-barista=\"${app.barista_id}\">View</button>${app.status==='interested'?`<button class=\"primary\" data-match-app=\"${app.id}\">Match</button>`:''}</div></div>"
if old not in s: raise SystemExit('applicant row target not found')
s=s.replace(old,new,1)
css='''.applicant-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:center}.applicant-main{display:flex;align-items:center;gap:13px;min-width:0}.applicant-actions{display:flex;gap:9px;align-items:center}.applicant-actions button{min-width:92px}@media(max-width:720px){.applicant-item{grid-template-columns:1fr;gap:14px;padding:18px 0}.applicant-main{align-items:flex-start}.applicant-main .avatar{width:48px;height:48px}.applicant-main .itemtext b{font-size:17px}.applicant-main .itemtext small{font-size:13px;line-height:1.45;overflow-wrap:normal;word-break:normal}.applicant-actions{display:grid;grid-template-columns:1fr 1fr;width:100%}.applicant-actions button{width:100%;min-width:0;padding:12px 14px}.applicant-actions button:only-child{grid-column:1/-1}.card:has(.applicant-item){padding:18px}.card:has(.applicant-item)>h3{font-size:21px;margin-bottom:8px}}'''
if '.applicant-item{' not in s:s=s.replace('.job-item{align-items:flex-start;gap:14px}',css+'\n.job-item{align-items:flex-start;gap:14px}',1)
p.write_text(s)
