from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
main='''<main id="home" class="bp-home">
  <section class="bp-hero">
    <div class="wrap bp-hero-grid">
      <div class="bp-hero-copy">
        <h1>Great cafés and<br>great baristas<br><em>belong together.</em></h1>
        <p>BaristaMatch is the easiest way for cafés and baristas to find each other.</p>
        <div class="bp-role-grid">
          <button class="bp-role-card" data-signup-role="barista"><span class="bp-role-icon">☕</span><span><strong>I’m a Barista</strong><small>Find café opportunities that fit you.</small><b>Join for free →</b></span></button>
          <button class="bp-role-card bp-hiring" data-signup-role="cafe_owner_manager"><span class="bp-role-icon">▦</span><span><strong>I’m Hiring</strong><small>Find and connect with great baristas.</small><b>Start hiring →</b></span></button>
        </div>
        <div class="bp-trust"><span>⌖ Local matches</span><span>◯ Private messaging</span><span>✓ Complete profiles</span><span>☕ Built for the coffee community</span></div>
      </div>
      <div class="bp-hero-visual">
        <img src="/assets/baristamatch-blueprint-v4.png" alt="Barista preparing latte art in a café" loading="eager">
        <div class="bp-phone-card"><div class="bp-phone-top">☕ BaristaMatch</div><strong>Aurora Café</strong><small>Miami, FL · Nearby</small><div class="bp-phone-pay">Barista opportunity</div><div class="bp-phone-tags"><span>Latte Art</span><span>Full-time</span></div><hr><small>Top match for you</small><div class="bp-mini-profile"><span>👤</span><div><b>Sofia Martinez</b><small>Latte Art Specialist</small></div></div><button type="button" data-signup-role="barista">View profile</button></div>
      </div>
    </div>
  </section>

  <section class="bp-how" id="how"><div class="wrap bp-how-grid">
    <div><div class="bp-kicker">HOW IT WORKS</div><h2>Simple steps. Better matches.</h2><div class="bp-steps"><article><span>⌕</span><b>1. Discover</b><p>Find cafés or baristas near you.</p></article><i>→</i><article><span>♡</span><b>2. Match</b><p>Connect when there’s genuine interest.</p></article><i>→</i><article><span>◯</span><b>3. Chat</b><p>Message directly and move forward.</p></article></div></div>
    <article class="bp-community"><div><h3>Made for the<br>coffee community</h3><p>BaristaMatch brings local cafés and talented baristas together.</p><ul><li>Built for real coffee people</li><li>Location-based matches</li><li>Private & secure messaging</li><li>Support when you need it</li></ul></div><div class="bp-community-photo"><img src="/assets/baristamatch-blueprint-v3.png" alt="Modern café interior"></div></article>
  </div></section>

  <section class="wrap bp-audience" id="baristas">
    <article class="bp-audience-card bp-barista-card"><div class="bp-audience-photo"><img src="/assets/baristamatch-blueprint-v2.png" alt="Barista working at an espresso machine"></div><div class="bp-audience-copy"><span>FOR BARISTAS</span><h2>Find a café<br>where you belong.</h2><ul><li>Create your profile for free</li><li>Discover nearby opportunities</li><li>Get matched by local cafés</li><li>Chat directly with employers</li></ul><button class="btn" data-signup-role="barista">Create my free profile</button><small>Baristas are always free.</small></div></article>
    <article class="bp-audience-card bp-cafe-card" id="cafes"><div class="bp-audience-copy"><span>FOR CAFÉS</span><h2>Hire great baristas.<br>Faster.</h2><ul><li>Post jobs in minutes</li><li>Find qualified local baristas</li><li>Review complete profiles</li><li>Message after matching</li></ul><button class="btn dark" data-signup-role="cafe_owner_manager">Start hiring</button><small>Create your café account to get started.</small></div><div class="bp-audience-photo"><img src="/assets/baristamatch-blueprint-v4.png" alt="Café owner reviewing applicants"></div></article>
  </section>

  <section class="bp-reasons" id="why"><div class="wrap"><h2>Why cafés and baristas love BaristaMatch</h2><div class="bp-reason-grid"><article><span>♙</span><div><b>Built for coffee people</b><p>Focused on the industry, not a generic job board.</p></div></article><article><span>⌖</span><div><b>Local first</b><p>Find opportunities and talent in your community.</p></div></article><article><span>♢</span><div><b>Private by design</b><p>Messaging opens after a real match.</p></div></article><article><span>☕</span><div><b>For every stage</b><p>From first job to growing café teams.</p></div></article></div></div></section>

  <section class="wrap bp-previews"><div class="bp-preview-head"><div><div class="bp-kicker">SEE THE EXPERIENCE</div><h2>Simple on both sides.</h2></div><p>One focused workspace for finding jobs, reviewing candidates, matching, and messaging.</p></div><div class="bp-preview-grid"><article><h3>Barista dashboard</h3><img src="/assets/baristamatch-blueprint-v4.png" alt="Barista dashboard preview"></article><article><h3>Café dashboard</h3><img src="/assets/baristamatch-blueprint-v3.png" alt="Café dashboard preview"></article><article><h3>Messages</h3><div class="bp-chat"><div class="bp-chat-head">← <b>Sofia Martinez</b></div><div class="bp-bubble">Hi! I saw your job post and I’m interested.</div><div class="bp-bubble mine">Thanks for reaching out. Your profile looks great.</div><div class="bp-bubble">Are you available for an interview this week?</div><div class="bp-chat-input">Type a message… <b>→</b></div></div></article></div></section>

  <section class="wrap bp-final" id="get-started"><div class="bp-final-art"><img src="/assets/baristamatch-blueprint-v2.png" alt="Latte art"></div><div><h2>Better matches. Stronger teams.<br>A better coffee community.</h2><p>Join cafés and baristas building the future of coffee.</p></div><button class="bp-final-choice" data-signup-role="barista"><b>I’m a Barista</b><span>Join for free →</span></button><button class="bp-final-choice" data-signup-role="cafe_owner_manager"><b>I’m Hiring</b><span>Start hiring →</span></button></section>
</main>'''
s=re.sub(r'<main id="home">.*?</main>',main,s,flags=re.S)
footer='''<footer class="bp-footer"><div class="wrap bp-footer-grid"><div class="bp-foot-brand"><div class="brand"><img src="/assets/favicon-transparent-v2.png" alt="BaristaMatch logo"><span>Barista<b>Match</b></span></div><p>Connecting cafés and baristas.<br>Brewing better opportunities.</p></div><div><b>For Baristas</b><a href="#baristas">Find Jobs</a><a href="#baristas">Create Profile</a><a href="/support.html">Help Center</a></div><div><b>For Cafés</b><a href="#cafes">Hire Baristas</a><a href="#cafes">Post a Job</a><a href="/support.html">Support</a></div><div><b>Resources</b><a href="#how">How it works</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></div><div><b>Company</b><a href="/support.html">Contact Us</a><a href="/privacy.html">Privacy Policy</a><a href="/terms.html">Terms of Service</a></div></div></footer>'''
s=re.sub(r'<footer class="wrap">.*?</footer>',footer,s,flags=re.S)
css='''
/* Blueprint-exact public homepage */
.bp-home{overflow:hidden}.bp-hero{background:linear-gradient(105deg,#fffaf4 0%,#fbf7f1 51%,#efe5d9 100%);border-bottom:1px solid var(--line)}.bp-hero-grid{min-height:620px;display:grid;grid-template-columns:1.02fr .98fr;align-items:center;gap:28px}.bp-hero-copy{padding:72px 0}.bp-hero-copy h1{font:850 clamp(50px,5.5vw,78px)/.99 Arial,sans-serif;letter-spacing:-.055em;margin:0 0 24px;color:#17110d}.bp-hero-copy h1 em{font-style:normal;color:var(--caramel)}.bp-hero-copy>p{font-size:18px;line-height:1.55;color:#40352e;max-width:570px;margin:0 0 28px}.bp-role-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;max-width:660px}.bp-role-card{border:1px solid var(--line);background:#fff8f1;border-radius:17px;padding:16px;text-align:left;display:grid;grid-template-columns:56px 1fr;gap:13px;align-items:center;box-shadow:0 8px 24px #32170808}.bp-role-card:hover{transform:translateY(-2px)}.bp-role-card.bp-hiring{background:#f3f8f1}.bp-role-icon{width:54px;height:64px;border-radius:12px;background:#f2e4d7;display:grid;place-items:center;font-size:26px}.bp-role-card strong,.bp-role-card small,.bp-role-card b{display:block}.bp-role-card strong{font-size:17px}.bp-role-card small{font-size:12px;color:var(--muted);line-height:1.4;margin:4px 0 9px}.bp-role-card b{font-size:12px;color:var(--caramel)}.bp-hiring b{color:var(--green)}.bp-trust{display:flex;gap:20px;flex-wrap:wrap;margin-top:26px;font-size:11px;font-weight:800;color:#34261d}.bp-hero-visual{height:620px;position:relative;overflow:hidden;border-radius:0 0 0 46px;background:#3e2518}.bp-hero-visual>img{width:100%;height:100%;object-fit:cover;object-position:72% 4%;filter:saturate(.92) contrast(1.03)}.bp-phone-card{position:absolute;right:7%;bottom:8%;width:230px;background:#fffdf9;border:1px solid #d9c9bb;border-radius:28px;padding:22px 17px;box-shadow:0 22px 55px #0004;transform:rotate(2deg);display:grid;gap:7px}.bp-phone-top{font-size:11px;font-weight:900;color:var(--caramel)}.bp-phone-card>strong{font-size:18px}.bp-phone-card small{font-size:11px;color:var(--muted)}.bp-phone-pay{font-weight:800;font-size:13px}.bp-phone-tags{display:flex;gap:5px}.bp-phone-tags span{font-size:9px;padding:4px 6px;background:#f3e8de;border-radius:99px}.bp-mini-profile{display:flex;gap:8px;align-items:center}.bp-mini-profile>span{width:34px;height:34px;background:#f3e6dc;border-radius:50%;display:grid;place-items:center}.bp-mini-profile b,.bp-mini-profile small{display:block;font-size:10px}.bp-phone-card button{border:1px solid var(--line);border-radius:9px;background:#fff;padding:8px;font-weight:800;font-size:11px}
.bp-how{padding:54px 0;background:#fffdf9}.bp-how-grid{display:grid;grid-template-columns:1fr 1fr;gap:34px;align-items:stretch}.bp-kicker{font-size:10px;font-weight:900;letter-spacing:.16em;color:#493326}.bp-how h2,.bp-previews h2{font-size:32px;margin:8px 0 28px}.bp-steps{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:12px;align-items:center}.bp-steps article{text-align:center;display:grid;gap:8px}.bp-steps article>span{margin:auto;width:58px;height:58px;border:1px solid #ead8c8;background:#fff7ef;border-radius:50%;display:grid;place-items:center;font-size:28px}.bp-steps p{font-size:12px;color:var(--muted);line-height:1.45;margin:0}.bp-steps i{font-style:normal;color:#d9aa82;font-size:24px}.bp-community{border:1px solid var(--line);border-radius:18px;background:#fff;display:grid;grid-template-columns:1fr 1.05fr;overflow:hidden}.bp-community>div:first-child{padding:24px}.bp-community h3{font-size:24px;margin:0 0 10px}.bp-community p{color:var(--muted);font-size:13px;line-height:1.5}.bp-community ul,.bp-audience ul{list-style:none;padding:0;margin:17px 0;display:grid;gap:10px}.bp-community li,.bp-audience li{font-size:13px}.bp-community li:before,.bp-audience li:before{content:'✓';color:var(--green);font-weight:900;margin-right:9px}.bp-community-photo{overflow:hidden}.bp-community-photo img{width:100%;height:100%;object-fit:cover;object-position:78% 17%}
.bp-audience{display:grid;grid-template-columns:1fr 1fr;gap:16px;padding:18px 0 32px}.bp-audience-card{min-height:330px;border-radius:18px;overflow:hidden;display:grid;grid-template-columns:1fr 1.06fr;border:1px solid var(--line);background:#fff}.bp-audience-photo{overflow:hidden;background:#28170f}.bp-audience-photo img{width:100%;height:100%;object-fit:cover}.bp-barista-card .bp-audience-photo img{object-position:8% 20%}.bp-cafe-card .bp-audience-photo img{object-position:85% 20%}.bp-audience-copy{padding:28px;display:flex;flex-direction:column;justify-content:center}.bp-barista-card .bp-audience-copy{background:linear-gradient(135deg,#321708,#57311c);color:#fff}.bp-audience-copy>span{display:inline-block;width:max-content;border-radius:6px;padding:5px 8px;background:#a95820;color:#fff;font-size:9px;font-weight:900}.bp-cafe-card .bp-audience-copy>span{background:#2f7c42}.bp-audience-copy h2{font-size:30px;line-height:1.05;margin:12px 0}.bp-barista-card .bp-audience-copy li{color:#fff}.bp-barista-card .bp-audience-copy small{color:#e9d9ca}.bp-audience-copy small{display:block;margin-top:8px;color:var(--muted);font-size:10px}.bp-audience-copy .btn{width:max-content}
.bp-reasons{padding:38px 0;background:#fffdf9;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.bp-reasons h2{text-align:center;font-size:28px;margin:0 0 28px}.bp-reason-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0}.bp-reason-grid article{display:flex;gap:12px;padding:12px 22px;border-right:1px solid var(--line)}.bp-reason-grid article:last-child{border-right:0}.bp-reason-grid article>span{width:44px;height:44px;flex:0 0 auto;border-radius:50%;background:#fff6ed;border:1px solid #ead8c8;display:grid;place-items:center;font-size:21px}.bp-reason-grid b{font-size:13px}.bp-reason-grid p{font-size:11px;color:var(--muted);line-height:1.45;margin:5px 0 0}
.bp-previews{padding:58px 0}.bp-preview-head{display:flex;justify-content:space-between;gap:30px;align-items:end;margin-bottom:24px}.bp-preview-head p{max-width:430px;color:var(--muted);line-height:1.55}.bp-preview-grid{display:grid;grid-template-columns:1fr 1fr .78fr;gap:14px}.bp-preview-grid>article{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px;overflow:hidden}.bp-preview-grid h3{font-size:13px;margin:0 0 10px}.bp-preview-grid img{width:100%;height:320px;object-fit:cover;object-position:50% 72%;border-radius:12px}.bp-chat{height:320px;border-radius:12px;background:#fbf7f1;padding:12px;display:flex;flex-direction:column;gap:9px}.bp-chat-head{padding-bottom:8px;border-bottom:1px solid var(--line);font-size:12px}.bp-bubble{max-width:82%;padding:9px 10px;border-radius:12px;background:#fff;border:1px solid #e7ddd2;font-size:11px;line-height:1.4}.bp-bubble.mine{margin-left:auto;background:var(--brown);color:#fff}.bp-chat-input{margin-top:auto;background:#fff;border:1px solid var(--line);border-radius:99px;padding:9px 12px;font-size:10px;color:var(--muted);display:flex;justify-content:space-between}.bp-chat-input b{color:var(--brown)}
.bp-final{min-height:180px;margin-bottom:38px;background:#fff;border:1px solid var(--line);border-radius:18px;display:grid;grid-template-columns:240px 1fr 185px 185px;align-items:center;overflow:hidden}.bp-final-art{height:100%;overflow:hidden}.bp-final-art img{width:100%;height:100%;object-fit:cover;object-position:18% 12%}.bp-final>div:nth-child(2){padding:25px}.bp-final h2{font-size:24px;margin:0 0 8px}.bp-final p{font-size:12px;color:var(--muted)}.bp-final-choice{margin:10px;border:1px solid var(--line);border-radius:14px;background:#fff;padding:18px;text-align:left}.bp-final-choice b,.bp-final-choice span{display:block}.bp-final-choice span{margin-top:8px;color:var(--caramel);font-size:11px;font-weight:800}
.bp-footer{background:#2b1408;color:#fff;padding:36px 0}.bp-footer-grid{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:34px}.bp-footer-grid>div:not(.bp-foot-brand){display:grid;align-content:start;gap:8px}.bp-footer-grid b{font-size:12px}.bp-footer-grid a,.bp-footer-grid p{color:#d7c5b9;font-size:11px;line-height:1.5}.bp-foot-brand .brand{margin-bottom:8px}.bp-foot-brand .brand img{width:34px;height:34px}.bp-footer .brand span{color:#fff}
@media(max-width:980px){.bp-hero-grid{grid-template-columns:1fr}.bp-hero-visual{height:460px;border-radius:28px;margin-bottom:28px}.bp-how-grid,.bp-audience,.bp-preview-grid{grid-template-columns:1fr}.bp-reason-grid{grid-template-columns:1fr 1fr}.bp-reason-grid article:nth-child(2){border-right:0}.bp-reason-grid article{border-bottom:1px solid var(--line)}.bp-final{grid-template-columns:170px 1fr 160px}.bp-final-choice:last-child{grid-column:3}.bp-footer-grid{grid-template-columns:2fr 1fr 1fr}}
@media(max-width:620px){.bp-hero-grid{min-height:auto}.bp-hero-copy{padding:42px 0 26px}.bp-hero-copy h1{font-size:44px}.bp-role-grid{grid-template-columns:1fr}.bp-trust{gap:10px 16px}.bp-hero-visual{height:390px;margin:0 -16px;border-radius:0}.bp-phone-card{width:190px;right:4%;bottom:5%}.bp-how{padding:38px 0}.bp-how-grid{gap:18px}.bp-steps{grid-template-columns:1fr}.bp-steps i{transform:rotate(90deg)}.bp-community{grid-template-columns:1fr}.bp-community-photo{height:190px}.bp-audience-card{grid-template-columns:1fr}.bp-audience-photo{height:240px}.bp-cafe-card .bp-audience-copy{order:2}.bp-reason-grid{grid-template-columns:1fr}.bp-reason-grid article{border-right:0}.bp-preview-head{display:block}.bp-preview-grid img{height:260px}.bp-final{grid-template-columns:1fr;margin-left:0;margin-right:0}.bp-final-art{height:150px}.bp-final>div:nth-child(2){padding:20px}.bp-final-choice,.bp-final-choice:last-child{grid-column:auto}.bp-footer-grid{grid-template-columns:1fr 1fr}.bp-foot-brand{grid-column:1/-1}}
'''
s=s.replace('</style>',css+'</style>',1)
p.write_text(s)
