from pathlib import Path

p=Path('dashboard.html')
s=p.read_text()

def replace_once(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'{label} marker missing')
    s=s.replace(old,new,1)

marker='.menu button[data-section="Messages"]:before{content:"✉"}'
add='.nav-badge{display:inline-grid;place-items:center;min-width:19px;height:19px;padding:0 5px;margin-left:7px;border-radius:99px;background:#d85d49;color:#fff;font-size:10px;font-weight:900;vertical-align:middle}.conversation-unread{display:inline-grid;place-items:center;min-width:20px;height:20px;padding:0 6px;border-radius:99px;background:var(--caramel);color:#fff;font-size:10px;font-weight:900;margin-left:auto}.notification-card{display:flex;align-items:center;justify-content:space-between;gap:14px}.notification-card button{width:auto}.notification-hint{font-size:12px;color:var(--muted)}'
if add not in s:
    replace_once(marker,marker+'\n'+add,'message css')

replace_once("let activeClient,currentUser,currentRole,currentView,currentProfile={},candidateProfiles=[],profileViews=[],marketJobs=[],applications=[],currentSection='Overview';","let activeClient,currentUser,currentRole,currentView,currentProfile={},candidateProfiles=[],profileViews=[],marketJobs=[],applications=[],notificationRows=[],notificationRealtimeChannel=null,currentSection='Overview';",'globals')

old="detail=app.job?.title||(isBarista?'Matched café':'Matched barista');return `<button class=\"conversation-row\" type=\"button\" data-conversation-app=\"${app.id}\" data-conversation-name=\"${escapeHtml(name)}\" data-conversation-detail=\"${escapeHtml(detail)}\"><span class=\"conversation-avatar\">${isBarista?'☕':'👤'}</span><span class=\"conversation-copy\"><strong>${escapeHtml(name)}</strong><small>${escapeHtml(detail)}</small></span></button>`"
new="detail=app.job?.title||(isBarista?'Matched café':'Matched barista'),unread=notificationRows.filter(n=>n.type==='message'&&!n.read_at&&n.application_id===app.id).length;return `<button class=\"conversation-row\" type=\"button\" data-conversation-app=\"${app.id}\" data-conversation-name=\"${escapeHtml(name)}\" data-conversation-detail=\"${escapeHtml(detail)}\"><span class=\"conversation-avatar\">${isBarista?'☕':'👤'}</span><span class=\"conversation-copy\"><strong>${escapeHtml(name)}</strong><small>${escapeHtml(detail)}</small></span>${unread?`<span class=\"conversation-unread\">${unread>99?'99+':unread}</span>`:''}</button>`"
replace_once(old,new,'conversation row')

replace_once("await loadInboxMessages();subscribeToConversation(applicationId);if(innerWidth<720)panel.scrollIntoView({behavior:'smooth',block:'start'});","await loadInboxMessages();await activeClient.rpc('mark_conversation_read',{p_application_id:applicationId}).catch(()=>{});await refreshNotifications(false);subscribeToConversation(applicationId);if(innerWidth<720)panel.scrollIntoView({behavior:'smooth',block:'start'});",'mark conversation read')

replace_once("const {error}=await activeClient.from('messages').insert({application_id:activeMessageApplicationId,sender_id:currentUser.id,body});button.disabled=false;\n  if(error){status.textContent=error.message||'Message could not be sent. Please try again.';return}","const {data:{session}}=await activeClient.auth.getSession();const response=await fetch('/api/send-message',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({application_id:activeMessageApplicationId,body})});const result=await response.json().catch(()=>({}));button.disabled=false;\n  if(!response.ok){status.textContent=result.error||'Message could not be sent. Please try again.';return}",'send inbox')

replace_once("const {error}=await activeClient.from('messages').insert({application_id:activeMessageApplicationId,sender_id:currentUser.id,body});button.disabled=false;button.textContent='Send';if(error){status.textContent=error.message||'Could not send message.';return}","const {data:{session}}=await activeClient.auth.getSession();const response=await fetch('/api/send-message',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({application_id:activeMessageApplicationId,body})});const result=await response.json().catch(()=>({}));button.disabled=false;button.textContent='Send';if(!response.ok){status.textContent=result.error||'Could not send message.';return}",'dialog send')

replace_once("async function applyToJob(jobId,button){button.disabled=true;button.textContent='Sending…';try{const {error}=await activeClient.from('applications').insert({job_id:jobId,barista_id:currentUser.id,status:'interested'});if(error)throw error;await loadMarketplaceData();openSection('Find Jobs',currentView,currentRole)}catch(error){button.disabled=false;button.textContent='Try again';alert(error.code==='23505'?'You already showed interest in this job.':(error.message||'We could not send your interest. Please try again.'))}}","async function applyToJob(jobId,button){button.disabled=true;button.textContent='Sending…';try{const {data:{session}}=await activeClient.auth.getSession();const response=await fetch('/api/apply-job',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({job_id:jobId})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'We could not send your interest.');await loadMarketplaceData();openSection('Find Jobs',currentView,currentRole)}catch(error){button.disabled=false;button.textContent='Try again';alert(error.message||'We could not send your interest. Please try again.')}}",'apply job')

replace_once("async function matchApplication(applicationId,button){button.disabled=true;button.textContent='Matching…';try{const {error}=await activeClient.from('applications').update({status:'matched'}).eq('id',applicationId);if(error)throw error;await loadMarketplaceData();openSection('Candidates',currentView,currentRole)}catch(error){button.disabled=false;button.textContent='Try again';alert(error.message||'We could not create this match.') }}","async function matchApplication(applicationId,button){button.disabled=true;button.textContent='Matching…';try{const {data:{session}}=await activeClient.auth.getSession();const response=await fetch('/api/match-application',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({application_id:applicationId})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'We could not create this match.');await loadMarketplaceData();await refreshNotifications(false);openSection('Candidates',currentView,currentRole)}catch(error){button.disabled=false;button.textContent='Try again';alert(error.message||'We could not create this match.') }}",'match application')

replace_once("const advancedSettings=canDelete?`<details class=\"card settings-card advanced-settings\"","const notificationSection=`<article class=\"card settings-card notification-card\"><div><h3>Notifications</h3><p>Unread-message badges and email alerts are on. Browser alerts can also appear while BaristaMatch is open.</p><div class=\"notification-hint\" id=\"notification-permission\">Browser notifications: ${typeof Notification==='undefined'?'not supported':Notification.permission}</div></div><button class=\"secondary\" type=\"button\" data-enable-notifications>${typeof Notification!=='undefined'&&Notification.permission==='granted'?'Enabled':'Enable'}</button></article>`;const advancedSettings=canDelete?`<details class=\"card settings-card advanced-settings\"",'notification settings')
replace_once("${passwordSection}</article>${advancedSettings}</div>`","${passwordSection}</article>${notificationSection}${advancedSettings}</div>`",'notification settings render')
replace_once("content.querySelectorAll('[data-match-app]').forEach(button=>button.onclick=()=>matchApplication(button.dataset.matchApp,button));const search=","content.querySelectorAll('[data-match-app]').forEach(button=>button.onclick=()=>matchApplication(button.dataset.matchApp,button));content.querySelectorAll('[data-enable-notifications]').forEach(button=>button.onclick=()=>enableBrowserNotifications(button));const search=",'notification bind')

funcs=r'''async function refreshNotifications(render=true){
  if(!activeClient||!currentUser)return;const {data,error}=await activeClient.from('notifications').select('id,type,title,body,application_id,created_at,read_at').eq('recipient_id',currentUser.id).order('created_at',{ascending:false}).limit(200);if(!error)notificationRows=data||[];updateUnreadBadges();if(render&&currentSection==='Messages')openSection('Messages',currentView,currentRole)
}
function updateUnreadBadges(){const unread=notificationRows.filter(n=>n.type==='message'&&!n.read_at).length;document.querySelectorAll('#menu button[data-section="Messages"]').forEach(button=>{button.querySelector('.nav-badge')?.remove();if(unread)button.insertAdjacentHTML('beforeend',`<span class="nav-badge" aria-label="${unread} unread messages">${unread>99?'99+':unread}</span>`)});document.title=unread?`(${unread}) Dashboard — BaristaMatch`:'Dashboard — BaristaMatch'}
function subscribeNotifications(){if(notificationRealtimeChannel)activeClient.removeChannel(notificationRealtimeChannel);notificationRealtimeChannel=activeClient.channel(`notifications-${currentUser.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_id=eq.${currentUser.id}`},payload=>{notificationRows.unshift(payload.new);updateUnreadBadges();if(payload.new.type==='message'&&typeof Notification!=='undefined'&&Notification.permission==='granted'&&document.visibilityState!=='visible'){new Notification(payload.new.title||'New BaristaMatch message',{body:payload.new.body||'Open BaristaMatch to reply.',icon:'/assets/favicon-32-v2.png'})}if(currentSection==='Messages')openSection('Messages',currentView,currentRole)}).subscribe()}
async function enableBrowserNotifications(button){if(typeof Notification==='undefined'){alert('Browser notifications are not supported on this device.');return}const permission=await Notification.requestPermission();button.textContent=permission==='granted'?'Enabled':'Enable';const hint=document.getElementById('notification-permission');if(hint)hint.textContent='Browser notifications: '+permission;if(permission==='granted')new Notification('BaristaMatch notifications enabled',{body:'You’ll see message alerts while BaristaMatch is running.',icon:'/assets/favicon-32-v2.png'})}
async function reportClientError(message,stack,metadata={}){try{let session=null;if(activeClient){const r=await activeClient.auth.getSession();session=r.data?.session||null}fetch('/api/report-error',{method:'POST',headers:{'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})},keepalive:true,body:JSON.stringify({source:'dashboard',message:String(message||'Unknown error'),stack:String(stack||''),page_url:location.href,user_agent:navigator.userAgent,metadata})}).catch(()=>{})}catch{}}
window.addEventListener('error',event=>reportClientError(event.message,event.error?.stack,{filename:event.filename,line:event.lineno,column:event.colno}));
window.addEventListener('unhandledrejection',event=>reportClientError(event.reason?.message||String(event.reason||'Unhandled promise rejection'),event.reason?.stack||'',{kind:'unhandledrejection'}));
'''
start_marker="async function start(){try{"
if funcs not in s:
    replace_once(start_marker,funcs+start_marker,'notification functions')

replace_once("await withTimeout(loadMarketplaceData(),10000,'Loading marketplace activity took too long.');document.getElementById('email').textContent=","await withTimeout(loadMarketplaceData(),10000,'Loading marketplace activity took too long.');await withTimeout(refreshNotifications(false),10000,'Loading notifications took too long.');subscribeNotifications();document.getElementById('email').textContent=",'startup notifications')
replace_once("document.getElementById('menu').innerHTML=view.menu.map((x,i)=>`<button class=\"${i?'':'active'}\" data-section=\"${x}\">${x}</button>`).join('');document.getElementById('menu').onclick=","document.getElementById('menu').innerHTML=view.menu.map((x,i)=>`<button class=\"${i?'':'active'}\" data-section=\"${x}\">${x}</button>`).join('');updateUnreadBadges();document.getElementById('menu').onclick=",'menu badge')

p.write_text(s)

pp=Path('privacy.html'); q=pp.read_text()
q=q.replace('applications, and matching activity.','applications, matching activity, messages between matched users, and notification activity.')
q=q.replace('basic technical information supplied by our hosting and authentication providers.','basic technical information supplied by our hosting and authentication providers. We may also collect error details, page URLs, browser information, and diagnostic logs when something fails so we can troubleshoot reliability problems.')
q=q.replace('Supabase for authentication, database, and file storage, and Vercel for hosting and delivery.','Supabase for authentication, database, realtime updates, and file storage; Vercel for hosting and delivery; and Resend for transactional service emails such as support, match, application, and message notifications.')
pp.write_text(q)
