from pathlib import Path
p=Path('dashboard.html');s=p.read_text()
# Add styles for a dedicated profile completion card that fills as completion increases.
insert='''.profile-progress-card{grid-column:span 2;display:grid;grid-template-columns:120px minmax(0,1fr);gap:22px;align-items:center;background:#fff;border:1px solid var(--line);border-radius:20px;padding:22px}.profile-progress-ring{--p:0;width:108px;height:108px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--caramel) calc(var(--p)*1%),#eee5dd 0);position:relative}.profile-progress-ring:after{content:"";position:absolute;inset:10px;background:#fff;border-radius:50%}.profile-progress-ring strong{position:relative;z-index:1;font-size:31px}.profile-progress-copy h3{margin:0 0 7px;font-size:18px}.profile-progress-copy p{margin:0;color:var(--muted);line-height:1.45}.profile-progress-track{height:8px;background:#eee5dd;border-radius:99px;overflow:hidden;margin-top:14px}.profile-progress-track i{display:block;height:100%;background:var(--caramel);border-radius:inherit}.profile-progress-link{margin-top:12px;border:0;background:transparent;color:var(--caramel);font-weight:800;padding:0}@media(max-width:720px){.profile-progress-card{grid-column:1/-1;grid-template-columns:92px minmax(0,1fr);gap:15px;padding:18px}.profile-progress-ring{width:84px;height:84px}.profile-progress-ring:after{inset:8px}.profile-progress-ring strong{font-size:24px}.profile-progress-copy h3{font-size:16px}.profile-progress-copy p{font-size:13px}.profile-progress-track{margin-top:10px}}
'''
if '.profile-progress-card{' not in s:s=s.replace('.mobile-nav{display:none}',insert+'.mobile-nav{display:none}',1)
# Replace only the barista profile strength stat with a dedicated progress card. Other cards/layout remain unchanged.
old='''<article class="wow-stat"><span class="wow-stat-label">Profile Strength <span class="profile-info" title="Complete profiles get better visibility and matching">ⓘ</span></span><strong>${score}%</strong><span class="wow-stat-trend">${score===100?'Profile ready':'Complete your profile for better matches'}</span>${baristaChart([24,38,22,55,42,66,48,82])}</article>'''
new='''<article class="profile-progress-card"><div class="profile-progress-ring" style="--p:${score}"><strong>${score}%</strong></div><div class="profile-progress-copy"><h3>${score===100?'Profile ready ✓':'Complete your profile'}</h3><p>${score===100?'Your profile is ready for better visibility and matching.':'Add a few more details to improve your visibility and match quality.'}</p><div class="profile-progress-track"><i style="width:${score}%"></i></div>${score<100?'<button class="profile-progress-link" data-go="My Profile">Continue profile →</button>':''}</div></article>'''
if old not in s: raise SystemExit('barista profile strength card target not found')
s=s.replace(old,new,1)
p.write_text(s)
