from pathlib import Path
p=Path('dashboard.html')
s=p.read_text()
old="""function updateUnreadBadges(){const unread=notificationRows.filter(n=>n.type==='message'&&!n.read_at).length;document.querySelectorAll('#menu button[data-section=\"Messages\"]').forEach(button=>{button.querySelector('.nav-badge')?.remove();if(unread)button.insertAdjacentHTML('beforeend',`<span class=\"nav-badge\" aria-label=\"${unread} unread messages\">${unread>99?'99+':unread}</span>`)});document.title=unread?`(${unread}) Dashboard — BaristaMatch`:'Dashboard — BaristaMatch'}
function subscribeNotifications(){if(notificationRealtimeChannel)activeClient.removeChannel(notificationRealtimeChannel);notificationRealtimeChannel=activeClient.channel(`notifications-${currentUser.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_id=eq.${currentUser.id}`},payload=>{notificationRows.unshift(payload.new);updateUnreadBadges();if(payload.new.type==='message'&&typeof Notification!=='undefined'&&Notification.permission==='granted'&&document.visibilityState!=='visible'){new Notification(payload.new.title||'New BaristaMatch message',{body:payload.new.body||'Open BaristaMatch to reply.',icon:'/assets/favicon-32-v2.png'})}if(currentSection==='Messages')openSection('Messages',currentView,currentRole)}).subscribe()}
"""
new="""function setNavBadge(section,count,label){document.querySelectorAll(`#menu button[data-section=\"${section}\"]`).forEach(button=>{button.querySelector('.nav-badge')?.remove();if(count)button.insertAdjacentHTML('beforeend',`<span class=\"nav-badge\" aria-label=\"${count} ${label}\">${count>99?'99+':count}</span>`)})}
function updateUnreadBadges(){const messages=notificationRows.filter(n=>n.type==='message'&&!n.read_at).length,applicationsUnread=notificationRows.filter(n=>n.type==='application'&&!n.read_at).length,matchesUnread=notificationRows.filter(n=>n.type==='match'&&!n.read_at).length,total=messages+applicationsUnread+matchesUnread;setNavBadge('Messages',messages,'unread messages');setNavBadge('Candidates',applicationsUnread,'new candidates');setNavBadge('Matches',matchesUnread,'new matches');document.title=total?`(${total}) Dashboard — BaristaMatch`:'Dashboard — BaristaMatch'}
async function refreshMarketplaceForNotification(type){if(!['application','match'].includes(type))return;try{await loadMarketplaceData();if((type==='application'&&currentSection==='Candidates')||(type==='match'&&currentSection==='Matches')||currentSection==='Overview')openSection(currentSection,currentView,currentRole)}catch(error){console.warn('Could not refresh marketplace after notification:',error)}}
function subscribeNotifications(){if(notificationRealtimeChannel)activeClient.removeChannel(notificationRealtimeChannel);notificationRealtimeChannel=activeClient.channel(`notifications-${currentUser.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_id=eq.${currentUser.id}`},payload=>{notificationRows.unshift(payload.new);updateUnreadBadges();if(typeof Notification!=='undefined'&&Notification.permission==='granted'&&document.visibilityState!=='visible'){new Notification(payload.new.title||'BaristaMatch update',{body:payload.new.body||'Open BaristaMatch for details.',icon:'/assets/favicon-32-v2.png'})}refreshMarketplaceForNotification(payload.new.type);if(payload.new.type==='message'&&activeMessageApplicationId===payload.new.application_id)loadInboxMessages()}).subscribe()}
"""
if old not in s: raise SystemExit('notification block target not found')
s=s.replace(old,new,1)
old2="""  if(!response.ok){status.textContent=result.error||'Message could not be sent. Please try again.';return}
  textarea.value='';textarea.style.height='auto';await loadInboxMessages();textarea.focus();
}"""
new2="""  if(!response.ok){status.textContent=result.error||'Message could not be sent. Please try again.';return}
  textarea.value='';textarea.style.height='auto';const stream=document.getElementById('chat-stream'),msg=result.message;if(stream&&msg){if(stream.querySelector('.message-empty'))stream.innerHTML='';stream.insertAdjacentHTML('beforeend',`<div class=\"chat-bubble-wrap mine\"><div class=\"chat-bubble\">${escapeHtml(msg.body||body)}</div><span class=\"chat-time\">${new Date(msg.created_at||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div>`);stream.scrollTop=stream.scrollHeight}else await loadInboxMessages();textarea.focus();
}"""
if old2 not in s: raise SystemExit('send message block target not found')
s=s.replace(old2,new2,1)
old3="""function openSection(name,view,role){if(name!=='Messages'&&messageRealtimeChannel){activeClient.removeChannel(messageRealtimeChannel);messageRealtimeChannel=null}currentSection=name;document.querySelectorAll('#menu button').forEach(button=>button.classList.toggle('active',button.dataset.section===name));document.querySelector('.top h1').textContent=name==='Overview'?'Dashboard':name;const isProfile=name==='My Profile'||name==='Café Profile';let html;if(name==='Overview')html=overviewHtml(view);else if(isProfile)html=profileHtml();else if(name==='Profile Views')html=profileViewsHtml();else if(name==='Find Jobs')html=jobsHtml();else if(name==='Job Posts')html=jobPostsHtml();else if(name==='Candidates')html=applicantHtml();else if(name==='Matches')html=matchesHtml();else if(name==='Messages')html=messagesInboxHtml();else html=sectionPages[role][name];document.getElementById('content').innerHTML=html;bindContentActions();window.scrollTo(0,0)}"""
new3="""function markSectionNotificationsRead(name){const type=name==='Candidates'?'application':name==='Matches'?'match':null;if(!type||!activeClient||!currentUser)return;const unread=notificationRows.filter(n=>n.type===type&&!n.read_at);if(!unread.length)return;const now=new Date().toISOString();unread.forEach(n=>n.read_at=now);updateUnreadBadges();activeClient.from('notifications').update({read_at:now}).eq('recipient_id',currentUser.id).eq('type',type).is('read_at',null).then(({error})=>{if(error)console.warn('Could not mark notifications read:',error)})}
function openSection(name,view,role){if(name!=='Messages'&&messageRealtimeChannel){activeClient.removeChannel(messageRealtimeChannel);messageRealtimeChannel=null}currentSection=name;document.querySelectorAll('#menu button').forEach(button=>button.classList.toggle('active',button.dataset.section===name));document.querySelector('.top h1').textContent=name==='Overview'?'Dashboard':name;const isProfile=name==='My Profile'||name==='Café Profile';let html;if(name==='Overview')html=overviewHtml(view);else if(isProfile)html=profileHtml();else if(name==='Profile Views')html=profileViewsHtml();else if(name==='Find Jobs')html=jobsHtml();else if(name==='Job Posts')html=jobPostsHtml();else if(name==='Candidates')html=applicantHtml();else if(name==='Matches')html=matchesHtml();else if(name==='Messages')html=messagesInboxHtml();else html=sectionPages[role][name];document.getElementById('content').innerHTML=html;bindContentActions();markSectionNotificationsRead(name);window.scrollTo(0,0)}"""
if old3 not in s: raise SystemExit('openSection target not found')
s=s.replace(old3,new3,1)
p.write_text(s)
print('patched realtime notifications, badges, chat refresh, and optimistic message rendering')
