-- BaristaMatch support ticket system
-- Run this once in Supabase SQL Editor.

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  ticket_id text not null unique,
  email text not null,
  name text,
  issue_type text not null,
  subject text not null,
  description text not null,
  page_url text,
  browser_info text,
  status text not null default 'new' check (status in ('new','investigating','fixed','closed')),
  resolution_note text,
  github_issue_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_email_idx on public.support_tickets (email);
create index if not exists support_tickets_status_idx on public.support_tickets (status);
create index if not exists support_tickets_created_at_idx on public.support_tickets (created_at desc);

alter table public.support_tickets enable row level security;

-- The browser never talks directly to this table.
-- Only the trusted Vercel server endpoint uses service_role.
grant select, insert, update on table public.support_tickets to service_role;
grant usage, select on sequence public.support_tickets_id_seq to service_role;

create or replace function public.set_support_ticket_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists support_ticket_updated_at on public.support_tickets;
create trigger support_ticket_updated_at
before update on public.support_tickets
for each row execute function public.set_support_ticket_updated_at();
