import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {loadTypescript} from './load-typescript.mjs';
const mobile=loadTypescript('mobile/lib/jobAccess.ts');
const html=readFileSync(new URL('../../dashboard.html',import.meta.url),'utf8');
function fn(name){const start=html.search(new RegExp(`^(?:async )?function ${name}\\(`,'m'));assert.ok(start>=0);const tail=html.slice(start),end=tail.slice(1).search(/\n(?=(?:async )?function )/);return tail.slice(0,end+1);}
const access={free_job_id:'job',free_job_expires_at:'2000-01-01',has_paid_access:false,can_create:false,active_job_count:0,server_time:new Date().toISOString(),clockOffset:0};
function website(extra={}){const ctx={Date,cafeJobAccess:access,marketJobs:[{id:'job',active:true,title:'Saved job'}],escapeHtml:s=>String(s??''),money:()=>'$20/hr',marketplaceNoticeHtml:()=>'',currentView:{},currentRole:'cafe_owner_manager',...extra};vm.createContext(ctx);vm.runInContext(['freeJobExpired','freeJobNotice','jobPostsHtml','toggleJob'].map(fn).join('\n'),ctx);return ctx;}
test('website expired job labels preserve edit access and route to plans without writing a job',async()=>{let destination;const ctx=website({openSection:name=>destination=name,activeClient:{from(){throw Error('must not write')}}});assert.match(ctx.jobPostsHtml(),/Free post expired/);assert.match(ctx.jobPostsHtml(),/data-edit-job/);assert.match(ctx.jobPostsHtml(),/View Pro plans/);await ctx.toggleJob('job',true,{});assert.equal(destination,'Subscription');});
test('website paid access does not label an original job expired',()=>{const ctx=website({cafeJobAccess:{...access,has_paid_access:true}});assert.equal(ctx.freeJobExpired({id:'job'}),false);assert.doesNotMatch(ctx.jobPostsHtml(),/Free post expired|View Pro plans/);});
test('mobile countdown uses server time instead of trusting an incorrect device clock',async()=>{const value=await mobile.loadCafeJobAccess(async()=>({data:{...access,server_time:'1999-12-01'},error:null}));assert.equal(mobile.freeJobExpired('job',value),false);assert.match(mobile.freeJobNotice('job',value),/Free post ends/);});
test('mobile invalid status or lookup failure stays blocked with a useful retry message',async()=>{for(const data of [null,{}, {...access,can_create:'yes'}, {...access,server_time:'invalid'}])await assert.rejects(mobile.loadCafeJobAccess(async()=>({data,error:null})),/could not verify/);await assert.rejects(mobile.loadCafeJobAccess(async()=>({data:access,error:{code:'internal'}})),/could not verify/);});
test('mobile statuses distinguish first free expiry, second-job restriction and the paid job limit',()=>{assert.match(mobile.jobAccessError({code:'PJB05'}),/30-day/);assert.match(mobile.jobAccessError({code:'PJB01'}),/one free job/);assert.match(mobile.jobAccessError({code:'PJB04'}),/3 active jobs/);assert.equal(mobile.freeJobExpired('another-job',access),false);assert.equal(mobile.freeJobExpired('job',{...access,has_paid_access:true}),false);});
test('expiry schedule executes only the private preservation sweep',()=>{const sql=readFileSync(new URL('../../supabase/migrations/20260929011238_schedule_free_job_expiration.sql',import.meta.url),'utf8');assert.match(sql,/create extension if not exists pg_cron/);assert.match(sql,/cron\.schedule\('baristamatch-expire-free-job-posts', '\* \* \* \* \*',\s*'select private\.expire_free_job_posts\(\)'\)/);assert.doesNotMatch(sql,/delete from|truncate /i);});
