import { useEffect,useRef,useState } from 'react';
import { ActivityIndicator,Alert,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { getCurrentContext } from '@/lib/session';
import { authenticatedApi } from '@/lib/api';

export default function Chat(){
  const {id,kind}=useLocalSearchParams<{id:string;kind?:'discovery'|'application'}>();const discovery=kind==='discovery';const [loading,setLoading]=useState(true),[messages,setMessages]=useState<any[]>([]),[body,setBody]=useState(''),[me,setMe]=useState(''),[name,setName]=useState('Conversation'),[sending,setSending]=useState(false);const scroll=useRef<ScrollView>(null);
  useEffect(()=>{load();const table=discovery?'discovery_messages':'messages',column=discovery?'match_id':'application_id';const channel=supabase.channel(`mobile-chat-${kind||'application'}-${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table,filter:`${column}=eq.${id}`},()=>loadMessages()).subscribe();return()=>{supabase.removeChannel(channel)}},[id,kind]);
  async function load(){const {user,role}=await getCurrentContext();if(!user)return router.replace('/login');setMe(user.id);if(discovery){const {data,error}=await supabase.from('discovery_matches').select('id,barista:profiles!discovery_matches_barista_id_fkey(display_name),cafe:profiles!discovery_matches_cafe_id_fkey(cafe_name)').eq('id',id).maybeSingle();if(error||!data)return unavailable();const match:any=data;setName(role==='barista'?(match.cafe?.cafe_name||'Café'):(match.barista?.display_name||'Barista'))}else{const {data,error}=await supabase.from('applications').select('id,barista:profiles!applications_barista_id_fkey(display_name),job:jobs(title,owner:profiles!jobs_owner_id_fkey(cafe_name))').eq('id',id).eq('status','matched').maybeSingle();if(error||!data)return unavailable();const app:any=data;setName(role==='barista'?(app.job?.owner?.cafe_name||'Café'):(app.barista?.display_name||'Barista'))}await loadMessages();setLoading(false)}
  function unavailable(){setLoading(false);Alert.alert('Conversation unavailable','This match could not be opened.',[{text:'Back',onPress:()=>router.back()}])}
  async function loadMessages(){const table=discovery?'discovery_messages':'messages',column=discovery?'match_id':'application_id';const {data,error}=await supabase.from(table).select('id,sender_id,body,created_at').eq(column,id).order('created_at',{ascending:true});if(error)return Alert.alert('Could not load messages',error.message);setMessages(data||[]);setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),80);if(!discovery){const {error:readError}=await supabase.rpc('mark_conversation_read',{p_application_id:id});if(readError)console.warn('Could not mark conversation read',readError.message)}}
  async function send(){const text=body.trim();if(!text||sending)return;setSending(true);setBody('');try{if(discovery){const {error}=await supabase.from('discovery_messages').insert({match_id:id,sender_id:me,body:text});if(error)throw error}else await authenticatedApi('/send-message',{application_id:id,body:text})}catch(error){setBody(text);Alert.alert('Message not sent',error instanceof Error?error.message:'Please try again.')}finally{setSending(false)}}
  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large" color="#321708"/></View></SafeAreaView>;return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View style={s.avatar}><Text>☕</Text></View><View><Text style={s.name}>{name}</Text><Text style={s.sub}>Mutual match · Private conversation</Text></View></View><ScrollView ref={scroll} style={s.stream} contentContainerStyle={s.streamContent}>{messages.length?messages.map(m=><View key={m.id} style={[s.bubbleWrap,m.sender_id===me&&s.mineWrap]}><View style={[s.bubble,m.sender_id===me&&s.mine]}><Text style={[s.text,m.sender_id===me&&s.mineText]}>{m.body}</Text></View><Text style={s.time}>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text></View>):<View style={s.empty}><Text style={{fontSize:38}}>👋</Text><Text style={s.emptyText}>Say hello and start the conversation.</Text></View>}</ScrollView><View style={s.compose}><TextInput value={body} onChangeText={setBody} placeholder="Message…" multiline style={s.input} placeholderTextColor="#9b8d84"/><Pressable disabled={sending||!body.trim()} onPress={send} style={[s.send,(sending||!body.trim())&&{opacity:.5}]}><Text style={s.sendText}>↑</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f0e9'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{height:72,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#eadfd5',flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:10},back:{width:38,height:38,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,color:'#321708',marginTop:-5},avatar:{width:42,height:42,borderRadius:21,backgroundColor:'#f3e8de',alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'900',color:'#24150d'},sub:{fontSize:11,color:'#746a61',marginTop:2},stream:{flex:1},streamContent:{padding:16,paddingBottom:24},bubbleWrap:{alignItems:'flex-start',marginBottom:9},mineWrap:{alignItems:'flex-end'},bubble:{maxWidth:'80%',backgroundColor:'#fff',borderWidth:1,borderColor:'#eadfd5',paddingHorizontal:14,paddingVertical:10,borderRadius:19,borderBottomLeftRadius:5},mine:{backgroundColor:'#321708',borderColor:'#321708',borderBottomLeftRadius:19,borderBottomRightRadius:5},text:{fontSize:15,lineHeight:21,color:'#2d211b'},mineText:{color:'#fff'},time:{fontSize:9,color:'#9a8c82',marginTop:3,marginHorizontal:5},compose:{backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#eadfd5',padding:10,flexDirection:'row',alignItems:'flex-end',gap:8},input:{flex:1,minHeight:45,maxHeight:110,borderWidth:1,borderColor:'#ddd0c6',borderRadius:23,paddingHorizontal:15,paddingTop:12,paddingBottom:10,fontSize:15,color:'#24150d'},send:{width:46,height:46,borderRadius:23,backgroundColor:'#321708',alignItems:'center',justifyContent:'center'},sendText:{color:'#fff',fontSize:22,fontWeight:'900'},empty:{alignItems:'center',paddingTop:120},emptyText:{color:'#746a61',marginTop:10}});
