alter table public.profiles
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.traffic_pageviews (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer_host text,
  device_type text not null default 'desktop',
  created_at timestamptz not null default now(),
  constraint traffic_pageviews_path_length check (char_length(path) between 1 and 300),
  constraint traffic_pageviews_referrer_length check (referrer_host is null or char_length(referrer_host) <= 200),
  constraint traffic_pageviews_device_type check (device_type in ('mobile','tablet','desktop'))
);

create index if not exists traffic_pageviews_created_at_idx
  on public.traffic_pageviews (created_at desc);

alter table public.traffic_pageviews enable row level security;
revoke all on table public.traffic_pageviews from anon, authenticated;
grant select, insert, delete on table public.traffic_pageviews to service_role;

create policy "No client access to private traffic analytics"
on public.traffic_pageviews for all to public
using (false) with check (false);
