const clean=(value,max)=>String(value??'').trim().slice(0,max);
function serverHeaders(extra={}){const key=process.env.SUPABASE_SECRET_KEY;const headers={apikey:key,'Content-Type':'application/json',...extra};if(key&&!key.startsWith('sb_secret_'))headers.Authorization=`Bearer ${key}`;return headers}
function rest(path,options={}){return fetch(`${process.env.SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...serverHeaders(),...(options.headers||{})}})}
function deviceType(userAgent){const ua=String(userAgent||'');if(/iPad|Tablet|PlayBook|Silk/i.test(ua))return'tablet';if(/Mobi|Android|iPhone|iPod/i.test(ua))return'mobile';return'desktop'}
async function owner(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const auth=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});if(!auth.ok)return null;const user=await auth.json();const check=await rest(`support_admins?user_id=eq.${encodeURIComponent(user.id)}&select=user_id&limit=1`);if(!check.ok)return null;return(await check.json()).length?user:null}
async function authenticatedUser(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const response=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});return response.ok?response.json():null}
async function record(req,res){const channel=req.body?.channel==='app'?'app':'web';if(channel==='app'&&!await authenticatedUser(req))return res.status(204).end();const fetchSite=clean(req.headers['sec-fetch-site'],30);if(channel==='web'&&fetchSite&&fetchSite!=='same-origin')return res.status(204).end();const path=clean(req.body?.path,300);if(!path.startsWith('/')||path.startsWith('/owner-dashboard')||path.startsWith('/support-admin'))return res.status(204).end();const payload={path,referrer_host:channel==='web'?(clean(req.body?.referrer_host,200)||null):null,device_type:channel==='app'?(req.body?.platform==='android'?'android':'ios'):deviceType(req.headers['user-agent']),channel};try{await rest('traffic_pageviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)})}catch(error){console.error('Analytics event failed',error?.message||error)}return res.status(204).end()}
async function report(req,res){if(!process.env.SUPABASE_PUBLISHABLE_KEY||!await owner(req))return res.status(403).json({error:'Owner access required'});try{const responses=await Promise.all(['owner_business_analytics','owner_subscription_analytics','owner_membership_controls'].map(name=>fetch(`${process.env.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:serverHeaders(),body:'{}'})));if(responses.some(response=>!response.ok))throw new Error(`Analytics query failed (${responses.map(response=>response.status).join('/')})`);const [business,subscriptions,controls]=await Promise.all(responses.map(response=>response.json()));return res.status(200).json({...business,subscriptions:{...subscriptions,...controls,metrics:{...subscriptions.metrics,complimentary:controls.complimentary_count}}})}catch(error){console.error('Owner analytics failed',error?.message||error);return res.status(500).json({error:'Could not load business analytics'})}}
async function membership(req,res){if(!process.env.SUPABASE_PUBLISHABLE_KEY||!await owner(req))return res.status(403).json({error:'Owner access required'});const userId=clean(req.body?.user_id,80),enabled=req.body?.enabled===true;if(!/^[0-9a-f-]{36}$/i.test(userId))return res.status(400).json({error:'Invalid café account'});const response=await rest(`cafe_subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=user_id,complimentary_access`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({complimentary_access:enabled})});if(!response.ok)return res.status(500).json({error:'Could not update partner access'});const updated=await response.json();if(updated.length!==1)return res.status(404).json({error:'Café subscription account not found'});return res.status(200).json({success:true,complimentary_access:updated[0].complimentary_access})}
export default async function handler(req,res){res.setHeader('Cache-Control','private, no-store');if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SECRET_KEY)return req.method==='POST'?res.status(204).end():res.status(503).json({error:'Analytics unavailable'});if(req.method==='POST')return record(req,res);if(req.method==='GET')return report(req,res);if(req.method==='PATCH')return membership(req,res);res.setHeader('Allow','GET, POST, PATCH');return res.status(405).end()}
