const clean=(v,max=5000)=>String(v??'').trim().slice(0,max);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function ah(extra={}){const key=process.env.SUPABASE_SECRET_KEY,h={apikey:key,'Content-Type':'application/json',...extra};if(key&&!key.startsWith('sb_secret_'))h.Authorization=`Bearer ${key}`;return h}
async function user(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const r=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});return r.ok?await r.json():null}
async function rest(p,o={}){return fetch(`${process.env.SUPABASE_URL}${p}`,{...o,headers:{...ah(),...(o.headers||{})}})}
async function mailFor(id){const r=await fetch(`${process.env.SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(id)}`,{headers:ah()});return r.ok?(await r.json()).email:null}
async function mail(to,subject,html){if(!to||!process.env.RESEND_API_KEY)return false;return (await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'BaristaMatch <updates@updates.baristajobmatch.com>',to:[to],reply_to:'hello@baristajobmatch.com',subject,html})})).ok}
export default async function handler(req,res){
  res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  const u=await user(req);if(!u?.id)return res.status(401).json({error:'Please log in again.'});const jobId=clean(req.body?.job_id,80);if(!jobId)return res.status(400).json({error:'Job is required.'});
  const jr=await rest(`/rest/v1/jobs?id=eq.${encodeURIComponent(jobId)}&active=eq.true&select=id,title,owner_id`);const job=jr.ok?(await jr.json())[0]:null;if(!job)return res.status(404).json({error:'This job is no longer available.'});
  const pr=await rest(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=role,display_name&limit=1`);const profile=pr.ok?(await pr.json())[0]:null;if(profile?.role!=='barista')return res.status(403).json({error:'Only baristas can show interest.'});
  const ir=await rest('/rest/v1/applications',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({job_id:jobId,barista_id:u.id,status:'interested'})});if(!ir.ok){const t=await ir.text();return res.status(t.includes('duplicate')?409:500).json({error:t.includes('duplicate')?'You already showed interest in this job.':'We could not send your interest.'})}
  let emailSent=false;try{const prefR=await rest(`/rest/v1/notification_preferences?user_id=eq.${encodeURIComponent(job.owner_id)}&select=email_matches&limit=1`);const pref=prefR.ok?(await prefR.json())[0]:null;if(pref?.email_matches!==false){const to=await mailFor(job.owner_id);const name=profile?.display_name||'A barista';emailSent=await mail(to,`${name} is interested in ${job.title}`,`<div style="max-width:560px;margin:auto;padding:28px;font-family:Arial,sans-serif;color:#321708;background:#fbf7f1;border-radius:18px"><h2>New interested barista</h2><p><strong>${esc(name)}</strong> showed interest in <strong>${esc(job.title)}</strong>.</p><p><a href="https://www.baristajobmatch.com/dashboard.html" style="color:#a95820;font-weight:700">Review candidates</a></p></div>`)} }catch(e){console.error('Application email notification failed',e?.message||e)}
  return res.status(200).json({success:true,email_sent:emailSent});
}
