function clean(v,max=5000){return String(v??'').trim().slice(0,max)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
async function sb(path,options={}){const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;return fetch(base+path,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}})}
async function adminUser(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const r=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)return null;const user=await r.json();const a=await sb(`/rest/v1/support_admins?user_id=eq.${encodeURIComponent(user.id)}&select=user_id&limit=1`);if(!a.ok)return null;const rows=await a.json();return rows.length?user:null}
async function sendMail(payload){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.ok}
function updateEmail(t,note,status){const label={new:'Received',in_progress:'In progress',waiting_user:'Waiting for your reply',resolved:'Resolved',closed:'Closed'}[status]||status;return `<!doctype html><html><body style="margin:0;background:#f4f0eb;font-family:Arial,sans-serif;color:#321708"><table width="100%" role="presentation"><tr><td align="center" style="padding:24px 12px"><table width="100%" role="presentation" style="max-width:560px;background:#fbf7f1;border-radius:18px"><tr><td style="padding:26px 24px"><div style="font-size:21px;font-weight:800">Barista<span style="color:#a95820">Match</span> <span style="font-size:14px;color:#746a61">Support</span></div><h1 style="font-size:25px;line-height:32px;margin:24px 0 10px">Your support ticket was updated</h1><p style="color:#55483f;font-size:15px;line-height:23px">Ticket <strong>${esc(t.ticket_id)}</strong> is now <strong>${esc(label)}</strong>.</p><div style="background:#fff;border:1px solid #e7ddd2;border-radius:12px;padding:17px;margin:18px 0"><div style="font-size:12px;color:#8a7566;font-weight:800;text-transform:uppercase">Update</div><div style="font-size:15px;line-height:23px;margin-top:6px">${esc(note||'Our support team has updated your request.').replaceAll('\n','<br>')}</div></div><p style="font-size:14px;line-height:21px;color:#746a61">Reply to this email if you need anything else.</p><p style="font-size:14px;color:#746a61">— BaristaMatch Support</p></td></tr></table></td></tr></table></body></html>`}
export default async function handler(req,res){
  if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SECRET_KEY||!process.env.SUPABASE_PUBLISHABLE_KEY)return res.status(503).json({error:'Support admin unavailable'});
  const admin=await adminUser(req);if(!admin)return res.status(403).json({error:'Admin access required'});
  if(req.method==='GET'){
    const r=await sb('/rest/v1/support_tickets?select=*&order=created_at.desc&limit=250');if(!r.ok)return res.status(500).json({error:'Could not load tickets'});const tickets=await r.json();
    const u=await sb('/rest/v1/support_ticket_updates?select=id,ticket_id,old_status,new_status,note,customer_emailed,created_at&order=created_at.desc&limit=500');const updates=u.ok?await u.json():[];
    return res.status(200).json({tickets,updates});
  }
  if(req.method!=='PATCH'){res.setHeader('Allow','GET, PATCH');return res.status(405).json({error:'Method not allowed'})}
  const ticketId=clean(req.body?.ticket_id,50),status=clean(req.body?.status,30),note=clean(req.body?.resolution_note,5000),notify=Boolean(req.body?.notify_customer);
  const allowed=new Set(['new','in_progress','waiting_user','resolved','closed']);if(!ticketId||!allowed.has(status))return res.status(400).json({error:'Invalid ticket update'});
  const existingR=await sb(`/rest/v1/support_tickets?ticket_id=eq.${encodeURIComponent(ticketId)}&select=*&limit=1`);const existing=existingR.ok?(await existingR.json())[0]:null;if(!existing)return res.status(404).json({error:'Ticket not found'});
  let emailed=false;if(notify){emailed=await sendMail({from:'BaristaMatch Support <updates@updates.baristajobmatch.com>',to:[existing.email],reply_to:'hello@baristajobmatch.com',subject:`Update on your BaristaMatch support ticket — ${ticketId}`,html:updateEmail(existing,note,status)})}
  const now=new Date().toISOString();const patch={status,resolution_note:note||null,updated_at:now,closed_at:['resolved','closed'].includes(status)?now:null};if(emailed)patch.last_customer_notified_at=now;
  const pr=await sb(`/rest/v1/support_tickets?ticket_id=eq.${encodeURIComponent(ticketId)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!pr.ok)return res.status(500).json({error:'Could not update ticket'});const updated=(await pr.json())[0];
  await sb('/rest/v1/support_ticket_updates',{method:'POST',body:JSON.stringify({ticket_id:ticketId,admin_user_id:admin.id,old_status:existing.status,new_status:status,note:note||null,customer_emailed:emailed})});
  return res.status(200).json({success:true,ticket:updated,customer_emailed:emailed});
}
